### ISSUE TITLE
Feature Request: JIRA Support for Ticketing

### ISSUE THREAD

**Issue by kraln** [houston/houston-core#123]
As per title, integration with JIRA for ticket tracking would be fantastic. Unfuddle is a severe limitation.

**Comment by boblail** [comment]
@kraln Thanks for the feature request!

I'm closing this here since I've extracted [houston-tickets](https://github.com/houston/houston-tickets/) from `houston-core`. Feel free to reopen the request on the other repo!

Also, if you're inclined, you can take a look at [how Houston implemented Ticket Tracking adapters](https://github.com/houston/houston-tickets/tree/master/lib/houston/adapters/ticket_tracker). If you're familiar with the JIRA API, it should be fairly trivial to define a new adapter to support it!
